version: '3.8'

services:
  fritz: 
    image: . 
    volumes:
      - ./buildprod/:/skile/build/distributions/
  webserver: 
    image: nginx:latest
    ports: 
      - 80:80
      - 443:443  
    volumes: 
      - ./nginx/conf/:/etc/nginx/conf.d/
      - ./certbot/www:/var/www/certbot/
      - ./certbot/conf/:/etc/nginx/ssl/
      - ./buildprod/:/usr/share/nginx/html  
  certbot: 
    image: certbot/certbot:latest 
    volumes: 
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw  
